// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAytH2bDCJtz5n5mbKjuwuZJelEzkMenuU',
    appId: '1:307024858504:web:264f6244d69cbef0befe3d',
    messagingSenderId: '307024858504',
    projectId: 'chat-app-3-78b33',
    authDomain: 'chat-app-3-78b33.firebaseapp.com',
    storageBucket: 'chat-app-3-78b33.appspot.com',
    measurementId: 'G-40FXWNMKZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbPSdbzTizzKrNr6fxHpwlbj7s7xSVOI4',
    appId: '1:307024858504:android:445d09f4513a7369befe3d',
    messagingSenderId: '307024858504',
    projectId: 'chat-app-3-78b33',
    storageBucket: 'chat-app-3-78b33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0NfwR6yAj5H82UPllL_tt7Y9QlJSbuVM',
    appId: '1:307024858504:ios:b7ac7f95925e1e55befe3d',
    messagingSenderId: '307024858504',
    projectId: 'chat-app-3-78b33',
    storageBucket: 'chat-app-3-78b33.appspot.com',
    iosClientId: '307024858504-anc5vhgim1apg9ma25e3gcl60ff57r5j.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarChatSetup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0NfwR6yAj5H82UPllL_tt7Y9QlJSbuVM',
    appId: '1:307024858504:ios:b086db2cfa9c5571befe3d',
    messagingSenderId: '307024858504',
    projectId: 'chat-app-3-78b33',
    storageBucket: 'chat-app-3-78b33.appspot.com',
    iosClientId: '307024858504-118jvr1egf2u26nos3gsbs3cktrjb1ch.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarChatSetup.RunnerTests',
  );
}
